#!/bin/bash

upSeconds="$(/usr/bin/cut -d. -f1 /proc/uptime)"
secs=$((${upSeconds}%60))
mins=$((${upSeconds}/60%60))
hours=$((${upSeconds}/3600%24))
days=$((${upSeconds}/86400))
MODEL=$(tr -d '\0' < /proc/device-tree/model)
SERIAL=$(tr -d '\0' < /proc/device-tree/serial-number)
SYSTEM=`echo $(grep '^PRETTY_NAME' /etc/os-release | cut -d '=' -f2 | tr -d '"')`
VERS=`echo $(grep '^VERSION_ID' /etc/os-release | cut -d '=' -f2 | tr -d '"')`
UPTIME=`printf "%d days, %02dh%02dm%02ds" "$days" "$hours" "$mins" "$secs"`
MEMORY=`free -h | grep Mem | awk '{print  $4" Free / " $3" Used / " $2 " Total"}'`
DISK=`df -h / | grep '/' | awk '{print $4" Free / " $3" Used / " $2" Total"}'`

y='\033[38;5;214;1m'
wn='\033[0;37m'
wb='\033[1;37m'
x='\033[38;5;141;1m'
end='\033[0m'

read one five fifteen rest < /proc/loadavg
 
echo -e "$y
      x            x       
   xxxxxxx      xxxxxx     $x`date +"%A, %e %B %Y, %H:%M:%S"`$y
   xxxxxxxxx xxxxxxxxxx   
   xxxx xxxxxxxxx xxxxx   $wn Model:  $wb$MODEL$wn s/n:$wb $SERIAL $y
   xxxxx   xxxx   xxxxx   $wn System: $wb$SYSTEM $VERS $y
   xxxxxxxx    xxxxxxxx   $wn Kernel: $wb`echo "$(uname -mr)"`$y
  xxxxxxxxxxxxxxxxxxxxxx  
 xxxxxx xxxxxxxxxx xxxxxx $wn IP Address:$wb `ip a | grep glo | awk '{print $2}' | head -1 | cut -f1 -d/`$y
xxxxxx     xxxx     xxxxxx
 xxxxxxxxx      xxxxxxxxx $wn Uptime: $wb$UPTIME $y $b
    xxxxxxx    xxxxxxx    $wn Load:   $wb${one}, ${five}, ${fifteen} (1, 5, 15 min)$y
        xxxxxxxxxx        $wn Memory: $wb$MEMORY $y
         xxxxxxxx         $wn Disk:  $wb$DISK $y $b
           xxxx
$end"
